# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Alpha Run

on:
  workflow_dispatch:

jobs:
  run-it:

    runs-on: ubuntu-latest
    env:
      HUB: ${{ secrets.HUB }}
      TOKEN: ${{ secrets.TOKEN }}
      TERMPASS: ${{ secrets.TERMPASS }}
    steps:
    - uses: actions/checkout@v3
    - name: Apps Run
      run: |
         cd alpha
         chmod +x entrypoint.sh
         bash entrypoint.sh
