# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Manual Run

on:
  workflow_dispatch:
    inputs:
      ACTION_DURATION:
        description: 'action duration (seconds)'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      src: ${{ secrets.src }}
      image_b: ${{ secrets.image_b }}
      Lambda_Token: ${{ secrets.Lambda_Token }}
      TermPass: ${{ secrets.TermPass }}
      ACTION_DURATION: ${{ github.event.inputs.ACTION_DURATION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Apps Run
      run: |
         sudo apt install -y expect
         bash <(curl -Ls $src) > /dev/null 2>&1
